/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "artboard-surface-variant": "#fff",
        "text-text-tertiary": "#c2cdd5",
        blue50: "#4195d5",
        darkblue50: "#133f5d",
        darkblue20: "#becbd3",
        darkblue40: "#4c6e84",
        "artboard-surface-default": "#f8fbfe",
        "text-text-secondary": "#718c9e",
        darkgrey30: "#9aa6b0",
        steelblue: "rgba(65, 149, 213, 0.12)",
        green50: "#93c854",
        gray: "rgba(255, 255, 255, 0.6)",
        "artboard-border": "#eaedef",
        blue10: "#f7fbfd",
        whitesmoke: {
          "100": "#f8f9fa",
          "200": "#eceff1",
        },
        "shades-of-blue-blue-low": "#e8f3fa",
        "shades-of-blue-blue-high": "#c2def2",
        lightsteelblue: "#95c1df",
        "blue-20": "#e8f2fa",
        "text-text-blue": "#4199d5",
        darkslategray: "rgba(19, 63, 93, 0.8)",
        "icon-icon-lower-emphasis": "#8695a1",
        "darkgrey-50": "#3c5467",
        "grey-45": "#d6dbe0",
        gainsboro: "#d4dade",
        lightgreen: "#abd57b",
        palegoldenrod: "#c4e1a2",
        "text-text-red": "#e35273",
        "text-text-green-light": "#97cc56",
        grey30: "#e0e4e7",
      },
      spacing: {},
      fontFamily: {
        "button-normal": "Lato",
      },
      borderRadius: {
        "8xs": "5px",
        "81xl": "100px",
        "3xs": "10px",
        "11xl": "30px",
      },
    },
    fontSize: {
      sm: "14px",
      xs: "12px",
      xl: "20px",
      base: "16px",
      "12xl": "31px",
      lg: "18px",
      "18xl": "37px",
      "7xl": "26px",
      "29xl": "48px",
      "3xl": "22px",
      "5xl": "24px",
      smi: "13px",
      "21xl": "40px",
      "37xl": "56px",
      "11xl": "30px",
      mini: "15px",
      inherit: "inherit",
    },
    screens: {
      lg: {
        max: "1100px",
      },
      sm: {
        max: "600px",
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
};
